// // controllers/paymentController.js

// const stripe = require("stripe")(process.env.STRIPE_SECRET_KEY); // Import and initialize Stripe with your secret key

// // Process payment
// const processPayment = async (req, res) => {
//   const { amount, currency, token } = req.body;

//   try {
//     // Create a charge using Stripe API
//     const charge = await stripe.charges.create({
//       amount: amount,
//       currency: currency,
//       source: token, // Payment token generated by Stripe.js or Checkout
//       description: 'Payment for order' // Description of the charge
//     });

//     // Payment successful, handle success response
//     res.status(200).json({ message: 'Payment processed successfully', charge });
//   } catch (error) {
//     // Payment failed, handle error response
//     console.error('Error in processPayment:', error);
//     res.status(500).json({ error: 'Payment processing failed' });
//   }
// };

// module.exports = { processPayment };
